# Generated by Django 3.0.7 on 2020-06-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
